@host=localhost:8000

###
POST /api/categorias
Host: {{host}}
Content-Type: application/ld+json

{
  "nome": "Porta moeda"
}

###
GET /api/categorias
Host: {{host}}

###
GET /api/categorias/2
Host: {{host}}

### Enviar todos os campos pra atualizar

PUT /api/categorias/3
Host: {{host}}
Content-Type: application/ld+json

{
  "nome": "Cestinho",
  "sobrenome": "kkkk"
}

### Enviar somente o campo que quero atualizar  

PATCH /api/categorias/3
Host: {{host}}
Content-Type: application/merge-patch+json

{
  "nome": "Cestinho"
}

###

DELETE /api/categorias/4
Host: {{host}}

